/**
 * Press coverage — October 2026 release.
 *
 * Source: the distribution partner's placement report (generated 2026-10-03).
 * One press release, published by each outlet below as a press release.
 * `visits` is the partner's estimate of the OUTLET's total monthly traffic —
 * not readership of this article — and is only ever shown with that label.
 *
 * Left out on purpose: the aggregator search link (not an outlet) and the
 * sites whose names imitate a well-known publication.
 */
export type Outlet = {
  name: string;
  /** media type as the report lists it */
  kind: string;
  /** estimated monthly visits to the outlet */
  visits: number;
  url: string;
  /** one-line descriptor, featured outlets only */
  note?: string;
};

export const pressRelease = {
  headline: "Every bed. Every vital.",
  headlineAccent: "Every second.",
  title: "Every Bed. Every Vital. Every Second. ASTA HealthTech Is Building the Intelligence Layer for Tomorrow\u2019s Hospitals.",
  date: "2\u20133 October 2026",
  sub: "ASTA\u2019s announcement of its Physiological Pattern Learning Model was published by 182 news outlets across India on 2\u20133 October 2026.",
} as const;

export { pressStats } from "./press-summary";

/** The lead placement, then eleven more — ordered by estimated monthly visits and recognition. */
export const featuredOutlets: Outlet[] = [
  { name: "The Daily Guardian", kind: "News Paper", visits: 301800, url: "https://thedailyguardian.com/news/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals-762655/", note: "English daily newspaper · iTV Network" },
  { name: "RT News24", kind: "News Portal", visits: 189750, url: "https://rtnews24.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/", note: "News portal · business" },
  { name: "Sangri Today", kind: "News Portal", visits: 175830, url: "https://www.sangritoday.com/spotlight/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals", note: "News portal" },
  { name: "Bhaskar Live", kind: "News Portal", visits: 161800, url: "https://bhaskarlive.in/business/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals-2148013", note: "News portal" },
  { name: "UP 18 News", kind: "News Portal", visits: 104760, url: "https://up18news.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/", note: "News portal" },
  { name: "SP Times", kind: "News Portal", visits: 40350, url: "https://www.sptimes.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals", note: "News portal" },
  { name: "Sangri Buzz", kind: "News Portal", visits: 36390, url: "https://www.sangribuzz.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals", note: "News portal" },
  { name: "Loktej English", kind: "News Portal", visits: 29600, url: "https://english.loktej.com/article/33142/every-bed--every-vital--every-second--asta-healthtech-is-building-the-intelligence-layer-for-tomorrow%E2%80%99s-hospitals", note: "English edition of the Loktej daily" },
  { name: "ekaainabharat", kind: "News Portal", visits: 22290, url: "https://www.ekaainabharat.com/en/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals", note: "News portal" },
  { name: "Attention India", kind: "News Portal", visits: 20700, url: "https://attentionindia.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals", note: "News portal" },
  { name: "Your Bangalore", kind: "News Portal", visits: 13800, url: "https://yourbangalore.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/", note: "City news · Bengaluru" },
  { name: "Hindustan Metro", kind: "News Portal", visits: 12600, url: "https://hindustanmetro.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals", note: "News portal" },
];

/** Every other outlet that published the release, largest first. */
export const moreOutlets: Outlet[] = [
  { name: "Hello Celebs", kind: "News Portal", visits: 20790, url: "https://www.hellocelebs.in/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "bollychakkar", kind: "News Portal", visits: 18810, url: "https://www.bollychakkar.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Best News Journal", kind: "News Portal", visits: 10740, url: "https://bestnewsjournal.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Central Herald", kind: "News Portal", visits: 8550, url: "https://centralherald.in/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Prakhar Jagaran", kind: "News Portal", visits: 8040, url: "https://prakharjagaran.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Khabare Rajasthan", kind: "News Portal", visits: 7800, url: "https://khabarerajasthan.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "MP Guardian", kind: "News Portal", visits: 7740, url: "https://mpguardian.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Ncr-Chronicle", kind: "News Portal", visits: 7530, url: "https://ncr-chronicle.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "jodhpurreporter", kind: "News Portal", visits: 7050, url: "https://jodhpurreporter.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Marudhar Chronicle", kind: "News Portal", visits: 7050, url: "https://marudharchronicle.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Pink City Now", kind: "News Portal", visits: 6900, url: "https://pinkcitynow.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "up-patrika", kind: "News Portal", visits: 6720, url: "https://up-patrika.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "India First News", kind: "News Portal", visits: 6360, url: "https://indiafirstnews.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "BizzSight", kind: "News Portal", visits: 6150, url: "https://bizzsight.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Delhi News Now", kind: "News Portal", visits: 5910, url: "https://delhinewsnow.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Live Jabalpur", kind: "News Portal", visits: 5910, url: "https://livejabalpur.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "lucnkowdigital", kind: "News Portal", visits: 5880, url: "https://lucnkowdigital.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Delhi News Watch", kind: "News Portal", visits: 5760, url: "https://delhinewswatch.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "maharashtra24x7", kind: "News Portal", visits: 5760, url: "https://maharashtra24x7.com/press-release/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Khammaghani Rajasthan", kind: "News Portal", visits: 5730, url: "https://khammaghanirajasthan.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Rajasthan Express", kind: "News Portal", visits: 5730, url: "https://rajasthanexpress.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "udaipurdispatch", kind: "News Portal", visits: 5730, url: "https://udaipurdispatch.com/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Delhi Morning Tribune", kind: "News Portal", visits: 5610, url: "https://delhimorningtribune.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Nagpur News Today", kind: "News Portal", visits: 5580, url: "https://nagpurnewstoday.com/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Shekhawati Samachar", kind: "News Portal", visits: 5580, url: "https://shekhawatisamachar.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The News Bharti", kind: "News Portal", visits: 5460, url: "https://thenewsbharti.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Business Point", kind: "News Portal", visits: 5000, url: "https://businesspoint.co.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "City Reporters", kind: "News Portal", visits: 5000, url: "https://cityreporters.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Company Voice", kind: "News Portal", visits: 5000, url: "https://companyvoice.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "MP Newsline", kind: "News Portal", visits: 4890, url: "https://mpnewsline.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Madhya Pradesh Mirror", kind: "News Portal", visits: 4860, url: "https://madhyapradeshmirror.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Bhopal Sun Times", kind: "News Portal", visits: 4770, url: "https://bhopalsuntimes.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Madhya Pradesh Herald", kind: "News Portal", visits: 4770, url: "https://madhyapradeshherald.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Deccan Messenger", kind: "News Portal", visits: 4770, url: "https://thedeccanmessenger.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News Track Bhopal", kind: "News Portal", visits: 4650, url: "https://newstrackbhopal.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The National Age", kind: "News Portal", visits: 4560, url: "https://thenationalage.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Daily News India", kind: "News Portal", visits: 4080, url: "https://dailynewsindia.co.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Story Writer", kind: "News Portal", visits: 4080, url: "https://storywriter.co.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "True Story India Magazine", kind: "Magazine", visits: 3840, url: "https://truestoryindia.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Economic India", kind: "News Portal", visits: 3810, url: "https://economicindia.co.in/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Prime India", kind: "News Portal", visits: 3270, url: "https://theprimeindia.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News Radian", kind: "News Portal", visits: 3210, url: "https://newsradian.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Venture Company News", kind: "News Portal", visits: 3120, url: "https://venturecompanynews.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Asia News", kind: "News Portal", visits: 3000, url: "https://assianews.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/57427/" },
  { name: "Awadh Express", kind: "News Portal", visits: 2500, url: "https://awadhexpress.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Bhubaneswar Journal", kind: "News Portal", visits: 2500, url: "https://bhubaneswarjournal.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Calcutta Current", kind: "News Portal", visits: 2500, url: "https://calcuttacurrent.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "deshdecoded", kind: "News Portal", visits: 2500, url: "https://deshdecoded.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Kashi Chronicle", kind: "News Portal", visits: 2500, url: "https://kashichronicle.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Lanka Express", kind: "News Portal", visits: 2500, url: "https://lankaexpress.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "MBI24 News", kind: "News Portal", visits: 2500, url: "https://www.mbi24news.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Nav Dhwani", kind: "News Portal", visits: 2500, url: "https://navdhwani.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Samachar Sansaar English", kind: "News Portal", visits: 2500, url: "https://en.samacharsansaar.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Shubh24", kind: "News Portal", visits: 2500, url: "https://www.shubh24.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Sikkim Samachar", kind: "News Portal", visits: 2500, url: "https://sikkimsamachar.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Srinagar Bulletin", kind: "News Portal", visits: 2500, url: "https://srinagarbulletin.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Buzz Bharat", kind: "News Portal", visits: 2500, url: "https://thebuzzbharat.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Visakhapatnam Today", kind: "News Portal", visits: 2500, url: "https://visakhapatnamtoday.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "My Country", kind: "News Portal", visits: 2310, url: "https://mycountry.co.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Hi Gujarat Gujarati", kind: "News Portal", visits: 2220, url: "https://higujarat.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Atulya Hindustan", kind: "News Portal", visits: 2190, url: "https://atulyahindustan.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Primex News International", kind: "News Portal", visits: 2190, url: "https://primexnewsinternational.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News21", kind: "News Portal", visits: 2130, url: "https://news21.co.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Prime News Tv", kind: "News Portal", visits: 2130, url: "https://primenewstv.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Financial News Day", kind: "News Portal", visits: 2100, url: "https://financialnewsday.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Real News", kind: "News Portal", visits: 2100, url: "https://real-news.co.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "A TO Z Newspaper", kind: "News Portal", visits: 2000, url: "https://a2znewspaper.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "agrasamachar", kind: "News Portal", visits: 2000, url: "https://agrasamachar.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Ahmedabad Bytes", kind: "News Portal", visits: 2000, url: "https://ahmedabadbytes.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "arthavarta", kind: "News Portal", visits: 2000, url: "https://arthavarta.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Attention Mumbai", kind: "News Portal", visits: 2000, url: "https://www.attentionmumbai.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Attention Worlds", kind: "News Portal", visits: 2000, url: "https://www.attentionworlds.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Banrasi News", kind: "News Portal", visits: 2000, url: "https://banrasinews.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Bengalore Buzz", kind: "News Portal", visits: 2000, url: "https://bengalorebuzz.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Bhiwandi Post", kind: "News Portal", visits: 2000, url: "https://bhiwandipost.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Bhura Bhai", kind: "News Portal", visits: 2000, url: "https://bhurabhai.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "BNI India", kind: "News Portal", visits: 2000, url: "https://bniindia.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Business Live Now", kind: "News Portal", visits: 2000, url: "https://www.businesslivenow.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Business Voice Now Magazine", kind: "Magazine", visits: 2000, url: "https://businessvoicenow.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "City Lights", kind: "News Portal", visits: 2000, url: "https://city-lights.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Daily Bulletin", kind: "News Portal", visits: 2000, url: "https://dailybulletin.co.in/index.php/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Dhanbad Express", kind: "News Portal", visits: 2000, url: "https://dhanbadexpress.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Dharma Dhwani", kind: "News Portal", visits: 2000, url: "https://dharmadhwani.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Direct Digital News", kind: "News Portal", visits: 2000, url: "https://directdigitalnews.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Entrepreneur Worlds", kind: "News Portal", visits: 2000, url: "https://www.entrepreneurworlds.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Famous Insider", kind: "News Portal", visits: 2000, url: "https://www.famousinsider.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Fast Report", kind: "News Portal", visits: 2000, url: "https://fastreport.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Financial Telegraph", kind: "News Portal", visits: 2000, url: "https://financialtelegraph.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "First Look Times", kind: "News Portal", visits: 2000, url: "https://www.firstlooktimes.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Forex News Times", kind: "News Portal", visits: 2000, url: "https://forexnewstimes.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "ghaziabadtimes", kind: "News Portal", visits: 2000, url: "https://ghaziabadtimes.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Glamstaan", kind: "News Portal", visits: 2000, url: "https://www.glamstaan.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Global News Index", kind: "News Portal", visits: 2000, url: "https://globalnewsindex.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Global News Tonight", kind: "News Portal", visits: 2000, url: "https://globalnewstonight.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Goa Khabar", kind: "News Portal", visits: 2000, url: "https://goakhabar.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Gujarat News Network", kind: "News Portal", visits: 2000, url: "https://gujaratnewsnetwork.com/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Guwahati Journal", kind: "News Portal", visits: 2000, url: "https://guwahatijournal.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Haryana Herald", kind: "News Portal", visits: 2000, url: "https://haryanaherald.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Hyderabad Social", kind: "News Portal", visits: 2000, url: "https://hyderabadsocial.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "hyderabadinews", kind: "News Portal", visits: 2000, url: "https://hyderabadinews.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "I Am Bhojpuriya.", kind: "News Portal", visits: 2000, url: "https://iambhojpuriya.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "ibtvlive", kind: "News Portal", visits: 2000, url: "http://ibtvlive.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "India Dazzle", kind: "News Portal", visits: 2000, url: "https://www.indiadazzle.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "India Headline", kind: "News Portal", visits: 2000, url: "https://indiaheadline.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Indian News Maker", kind: "News Portal", visits: 2000, url: "https://indiannewsmaker.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Influencive India", kind: "News Portal", visits: 2000, url: "https://influenciveindia.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Jaipur Bytes", kind: "News Portal", visits: 2000, url: "https://jaipurbytes.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Jaipur Kiran", kind: "News Portal", visits: 2000, url: "https://www.jaipurkiran.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Jaipur-Mirror", kind: "News Portal", visits: 2000, url: "https://www.jaipur-mirror.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Just News Now", kind: "News Portal", visits: 2000, url: "https://justnewsnow.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Kamal News India", kind: "News Portal", visits: 2000, url: "https://kamalnewsindia.com/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Kannada Chronicle", kind: "News Portal", visits: 2000, url: "https://kannadachronicle.com/blog/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Kanpur Live", kind: "News Portal", visits: 2000, url: "https://kanpurlive.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "khabareludhiana", kind: "News Portal", visits: 2000, url: "https://khabareludhiana.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Kochi Khabar", kind: "News Portal", visits: 2000, url: "https://kochikhabar.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "konkanjournal", kind: "News Portal", visits: 2000, url: "https://konkanjournal.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Latest Gold News", kind: "News Portal", visits: 2000, url: "https://latestgoldnews.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Madras Journal", kind: "News Portal", visits: 2000, url: "https://madrasjournal.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Marudhar Bharti", kind: "News Portal", visits: 2000, url: "https://www.marudharbharti.com/en/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Nagpur Note", kind: "News Portal", visits: 2000, url: "https://nagpurnote.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Nation Republiq", kind: "News Portal", visits: 2000, url: "https://www.nationrepubliq.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "New India Herald", kind: "News Portal", visits: 2000, url: "https://newindiaherald.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News Bolt", kind: "News Portal", visits: 2000, url: "https://en.newsbolt.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "News eContent", kind: "News Portal", visits: 2000, url: "https://newsecontent.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News On Board", kind: "News Portal", visits: 2000, url: "https://www.newsonboard.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "News Room Buzz", kind: "News Portal", visits: 2000, url: "https://newsroombuzz.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News Scoop", kind: "News Portal", visits: 2000, url: "https://news-scoop.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News Supply Daily", kind: "News Portal", visits: 2000, url: "https://newssupplydaily.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News Wire Delhi", kind: "News Portal", visits: 2000, url: "https://newswiredelhi.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "News Wire India", kind: "News Portal", visits: 2000, url: "https://newswireindia.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Noida Express", kind: "News Portal", visits: 2000, url: "https://noidaexpress.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Patna Patrika", kind: "News Portal", visits: 2000, url: "https://patnapatrika.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Pune Metro News", kind: "News Portal", visits: 2000, url: "https://punemetronews.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Punjab Bytes", kind: "News Portal", visits: 2000, url: "https://english.punjabbytes.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "ranchichronicle", kind: "News Portal", visits: 2000, url: "https://ranchichronicle.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "rashtraved", kind: "News Portal", visits: 2000, url: "https://rashtraved.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Real News Magazine", kind: "Magazine", visits: 2000, url: "https://realnewsmagazine.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Sahitya Hindustan", kind: "News Portal", visits: 2000, url: "https://sahityahindustan.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Sangri Times", kind: "News Portal", visits: 2000, url: "https://en.sangritimes.com/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Satya Buzz", kind: "News Portal", visits: 2000, url: "https://satyabuzz.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "SNB India News", kind: "News Portal", visits: 2000, url: "https://snbindianews.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Star News Line", kind: "News Portal", visits: 2000, url: "https://starnewsline.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Startup Babu", kind: "News Portal", visits: 2000, url: "https://www.startupbabu.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Swatantra Vaani", kind: "News Portal", visits: 2000, url: "https://swatantravaani.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Talk Pedia", kind: "News Portal", visits: 2000, url: "https://www.talkpedia.in/lifestyle/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "Telagana Talks", kind: "News Portal", visits: 2000, url: "https://telaganatalks.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Thank You Bharat", kind: "News Portal", visits: 2000, url: "https://thankyoubharat.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The 24 Nation", kind: "News Portal", visits: 2000, url: "https://the24nation.com/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Bharat Journal", kind: "News Portal", visits: 2000, url: "https://thebharatjournal.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Big India", kind: "News Portal", visits: 2000, url: "https://thebigindia.co.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Daily Beat", kind: "News Portal", visits: 2000, url: "https://thedailybeat.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "The Grand Media", kind: "News Portal", visits: 2000, url: "https://thegrandmedia.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Iconic News", kind: "News Portal", visits: 2000, url: "https://theiconicnews.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Indian Journal", kind: "News Portal", visits: 2000, url: "https://theindianjournal.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Msme News", kind: "News Portal", visits: 2000, url: "https://themsmenews.com/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Nation Times", kind: "News Portal", visits: 2000, url: "https://thenationtimes.co.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The National Daily", kind: "News Portal", visits: 2000, url: "https://thenationaldaily.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The News Cartel", kind: "News Portal", visits: 2000, url: "https://thenewscartel.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Samay", kind: "News Portal", visits: 2000, url: "https://thesamay.co.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Startup Story", kind: "News Portal", visits: 2000, url: "https://thestartupstory.co.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "The Times24", kind: "News Portal", visits: 2000, url: "https://thetimes24.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Think Of India", kind: "News Portal", visits: 2000, url: "https://www.thinkof-india.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals" },
  { name: "True Times", kind: "News Portal", visits: 2000, url: "https://truetimes.in/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Urban News Online", kind: "News Portal", visits: 2000, url: "https://urbannewsonline.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Vaani Live 24", kind: "News Portal", visits: 2000, url: "https://vaanilive24.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "vartaone", kind: "News Portal", visits: 2000, url: "https://vartaone.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Vishva Samvaad", kind: "News Portal", visits: 2000, url: "https://vishvasamvaad.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Vizag Mirror", kind: "News Portal", visits: 2000, url: "https://vizagmirror.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "World News Forall", kind: "News Portal", visits: 2000, url: "https://worldnewsforall.com/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
  { name: "Wow Entrepreneurs", kind: "News Portal", visits: 2000, url: "https://wowentrepreneurs.in/index.php/2026/10/02/every-bed-every-vital-every-second-asta-healthtech-is-building-the-intelligence-layer-for-tomorrows-hospitals/" },
];

/** The release in four parts, in ASTA's own words, shortened. */
export const pressStory = [
  {
    n: "01",
    head: "Monitors show numbers. Patterns tell the story.",
    body: "The Physiological Pattern Learning Model reads heart rate, SpO\u2082, blood pressure and respiratory rate as trajectories, looks for deterioration patterns, and forecasts each vital at +15 and +30 minutes with the uncertainty shown.",
  },
  {
    n: "02",
    head: "No new monitors required.",
    body: "A camera faces the bedside monitor, not the patient. Computer vision turns the display into structured, time-stamped vitals with no proprietary API and no hardware connection.",
  },
  {
    n: "03",
    head: "Giving time back to clinicians.",
    body: "One intelligence layer across monitored beds that captures vitals continuously, identifies meaningful change, and directs attention to the patients who need it most. Decision support: the doctor remains the decision-maker.",
  },
  {
    n: "04",
    head: "Made in India. Built for the world.",
    body: "Built in Bengaluru by a founding team spanning medicine, AI and enterprise technology, with support from AIC-SEED, MeitY Startup Hub, IISER Pune and NIT Andhra Pradesh.",
  },
] as const;

export const pressFacts = [
  { value: "100M+", label: "labelled monitor frames" },
  { value: "15+", label: "monitor OEM brands" },
  { value: "10+", label: "hospitals in India" },
] as const;
